# Generated by Django 5.0.4 on 2024-06-19 14:44

from django.db import migrations


def assign_age_group(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')
    persons = person_model.objects.all()

    for person_records in persons:
        if person_records.age < 13:
            person_records.age_group = 'Child'
        elif person_records.age < 18:
            person_records.age_group = 'Teen'
        else:
            person_records.age_group = 'Adult'

        # person_records.save()
    person_model.objects.bulk_update(persons, ['age_group'])


def return_age_group_default(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')
    persons = person_model.objects.all()

    default_age_group = person_model._meta.get_field('age_group').default

    for person in persons:
        person.age_group = default_age_group
        # person.save()

    person_model.objects.bulk_update(persons, ['age_group'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [migrations.RunPython(assign_age_group, reverse_code=return_age_group_default)
                  ]
