# Generated by Django 5.0.4 on 2024-06-19 15:55

from django.db import migrations


def apply_new_rarity(apps, schema_editor):
    item = apps.get_model('main_app', 'Item')
    items = item.objects.all()

    for item_model in items:
        if item_model.price < 11:
            item_model.rarity = 'Rare'
        elif item_model.price < 21:
            item_model.rarity = 'Very Rare'
        elif item_model.price < 31:
            item_model.rarity = 'Extremely Rare'
        else:
            item_model.rarity = 'Mega Rare'
        # item_model.save()

    item.objects.bulk_update(items, ['rarity'])


def return_default_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    items = item_model.objects.all()

    default_rarity = item_model._meta.get_field('rarity').default

    for item_record in items:
        item_record.rarity = default_rarity
        # item_record.save()
    #
    item_model.objects.bulk_update(items, ['rarity'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0011_item'),
    ]
    operations = [
        migrations.RunPython(apply_new_rarity, reverse_code=return_default_rarity)
    ]
