# Generated by Django 5.0.4 on 2024-06-19 19:45

from django.db import migrations
from django.utils import timezone


def set_delivery_warranty(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    for order in order_model.objects.all():
        if order.status == 'Pending':
            order.delivery = order.order_date + timezone.timedelta(days=3)
            order.save()
        elif order.status == 'Completed':
            order.warranty = 24
            order.save()
        else:
            order.delete()


def reverse_code(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')
    for order in order_model.objects.all():
        if order.status == 'Pending':
            order.delivery = None
        elif order.status == 'Completed':
            order.warranty = "No warranty"
        order.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(set_delivery_warranty, reverse_code=reverse_code)
    ]
