# Generated by Django 5.0.4 on 2024-06-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='work_full_time',
            new_name='works_full_time',
        ),
    ]
